# Generated by Django 4.2.3 on 2024-02-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_course_entrance_code_homework"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="grading_criteria",
            field=models.TextField(default="No grading criteria set"),
        ),
        migrations.AddField(
            model_name="homework",
            name="problems",
            field=models.TextField(default="No problems assigned"),
        ),
    ]
