# Generated by Django 4.2.3 on 2024-02-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_problem_solution"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultipleChoiceProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("choices", models.JSONField()),
                ("correct_answer", models.CharField(max_length=1)),
                (
                    "homework",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multiple_choice_problems",
                        to="accounts.homework",
                    ),
                ),
            ],
        ),
    ]
