# Generated by Django 5.0.2 on 2024-07-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_mcqresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='grades',
            field=models.JSONField(default=dict),
        ),
    ]
