# Generated by Django 5.0.2 on 2024-07-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_badge_user_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='criteria',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.ImageField(upload_to='badge_images/'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
